### PR TITLE
Context menu fix. Fixes #128.

### LINKED ISSUE #128: Right-click context menu doesn't work
It's impossible to delete a message/picture/object from the chat. It was working previously.
cant_remove_object
The web inspector pops up instead. is this only my problem?
Thanks.
Palkoc

### PR DESCRIPTION
**Pull request by sethk**
In debug mode, you can hold control + click to bring up the “Inspect Element.” Otherwise, this menu interferes with the JavaScript contextmenu event.

### CODE REVIEW

File: Messenger/AppDelegate.mm [hunk 1]
```diff
@@ -186,6 +186,7 @@ - (void)applicationDidFinishLaunching:(NSNotification*)notification {
   #if 0
   webView.customUserAgent = @"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12";
   #endif // 0
+  webView.maintainsBackForwardList = NO;
```
Comment (rsms) [inline Messenger/AppDelegate.mm:189]: Why?

File: Messenger/AppDelegate.mm [hunk 2]
```diff
@@ -755,6 +756,18 @@ - (WebView *)webView:(WebView *)sender createWebViewWithRequest:(NSURLRequest *)
 }
 
 
+- (NSArray *)webView:(WebView *)sender
+contextMenuItemsForElement:(NSDictionary *)element
+    defaultMenuItems:(NSArray *)defaultMenuItems {
+  #if DEBUG
+    if (([NSEvent modifierFlags] & NSControlKeyMask) == NSControlKeyMask) {
```
Comment (rsms) [inline Messenger/AppDelegate.mm:763]: FTR: Simply having the result of a mask operation be implicitly cast to a bool is usually more readable, i.e.

``` mm
if ([NSEvent modifierFlags] & NSControlKeyMask) {
```

**Comment by rsms** [comment]
Wouldn't this _always_ bring up the "debug menu" for users who use ctrl-click to bring up their menu? (It's the default way to show context menus on Mac)

You might want to consider using the semantically more appropriate option/alt key instead, as it would work for both right-clicking and ctrl-clicking.

**Comment by sethk** [comment]
Yeah, Option+secondary click is a good idea. I'll change it.

File: Messenger/AppDelegate.mm (hunk 2 above)
Comment (sethk) [inline Messenger/AppDelegate.mm:763]: I used to do that, but then I realized that implicitly casting a bitmask to an ObjC BOOL (which is an unsigned char) can fail if it's happening through a method argument because only the lowest bit, or lower 8 bits will be checked (depending on the compiler, optimization level, etc.).

In this case, it's just a C conditional, so any value other than 0 is fine. I'll change it.

File: Messenger/AppDelegate.mm (hunk 1 above)
Comment (sethk) [inline Messenger/AppDelegate.mm:189]: This removes the “Forward“ and “Back“ actions from the menu as well, since those seem to just cause problems in this app. However, maybe you still want them to show up in debug mode?

File: Messenger/AppDelegate.mm (hunk 2 above)
Comment (rsms) [inline Messenger/AppDelegate.mm:763]: Oh man, I know — objc BOOL is the worst, ha ha.

File: Messenger/AppDelegate.mm (hunk 1 above)
Comment (rsms) [inline Messenger/AppDelegate.mm:189]: Makes sense.

**Comment by rsms** [comment]
FTR: Made the suggested change to use alt/option instead of ctrl

**Comment by rsms** [comment]
Landed in release 0.1.4
